version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: >
      bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py createsuperuser && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8002:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=uniship
      - DB_USER=uniship
      - DB_PASS=KLSKDFLSK!##jkslö=)
      - DB_PORT=5433