version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: >
      bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py createsuperuser && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8002:8000"
    environment:
      - DB_HOST=db_host_ip
      - DB_NAME=steam
      - DB_USER=root
      - DB_PASS=dbpassword
      - DB_PORT=dbport
      - DJANGO_SECRET_KEY=django_secret_key